-- create table model
CREATE TABLE public.model (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(255) NOT NULL,
    description  varchar(1000),
    dateOfEntry  timestamp NOT NULL,  --not required but this will when it was first added
    lastModified timestamp NOT NULL,  --not required but this will when it was last modified
    createdBy    varchar(255),  --not required but this will track who added it
    company      varchar(255)
);

-- create table trueToSize
CREATE TABLE public.stats (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modelId      integer NOT NULL,
    size         integer NOT NULL,
    dateOfEntry  timestamp NOT NULL,  --not required but this will when it was first added
    lastModified timestamp NOT NULL,  --not required but this will when it was last modified
    createdBy    varchar(255),  --not required but this will track who added it
    CONSTRAINT model_stats_fkey FOREIGN KEY (modelId)
      REFERENCES public.model (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);
